### PR TITLE
fix reuse of storybook decorators in jest tests

### PR DESCRIPTION
**Pull request by yannbf**
Hey @takefumi-yoshii I read this really nice article you wrote: https://zenn.dev/takepepe/articles/reusable-story-playfn

And I noticed you mentioned that `composeStories` does not reuse MSW settings. That is actually not correct, it's just that in order to reuse more settings coming from decorators etc. you need to define the [global Storybook config](https://github.com/storybookjs/testing-react#global-config) as part of your jest setup file.
In this PR, I show how to do that, and you can see that things become simpler, while the tests still pass correctly.

Thank you so much for using `@storybook/testing-react`, as well as writing that super nice blog post!

### CODE REVIEW

**Comment by takefumi-yoshii** [comment]
@yannbf Please let me know if you know, I want to some test case to use MSW `server.use`. 
How do I reference an server instance?

**Comment by yannbf** [comment]
> @yannbf Please let me know if you know, I want to some test case to use MSW `server.use`. How do I reference an server instance?

Sure thing! 
You can use [getWorker](https://github.com/mswjs/msw-storybook-addon/blob/main/packages/msw-addon/src/mswDecorator.ts#L64) from the msw-storybook-addon, which returns the running MSW instance. In the context of a browser, it returns the MSW worker, in the context of node, it returns the MSW server:

```
import { getWorker } from "msw-storybook-addon";
import type { SetupServerApi } from 'msw/lib/types/node';

// execute this wherever you need, the type cast is only necessary if you want to use typescript
const server = getWorker() as SetupServerApi
```

**Comment by takefumi-yoshii** [comment]
@yannbf Great, it's works so fine! Let me ask you an additional question.
It took me a while to notice this difference.

```tsx
// wont pass ❌
const mock = jest.fn();
const server = getWorker();
server.use(createUserHandler({ mock }));
const { getByRole } = render(<Default />);
```

```tsx
// will pass ✅
const mock = jest.fn();
const server = getWorker();
const { getByRole } = render(<Default />);
server.use(createUserHandler({ mock }));
```

Is it okay to intercept after render?

**Comment by yannbf** [comment]
What's your use case? Unfortunately the decorator of msw-storybook-addon will reset the mocks:
https://github.com/mswjs/msw-storybook-addon/blob/main/packages/msw-addon/src/mswDecorator.ts#L83
I guess it'd be ok to set extra mocks after the component's first render, but depending on what you do it might be tricky?

So if you want a seamless experience that just reuses the mocks from Storybook, you could use the solution from this PR.
If you want to do something extra, maybe it will work as your suggestion, or maybe it would be better to not use the `globalConfig` (though you lose all decorators) and go with what you had prior to this PR 🤔

**Comment by takefumi-yoshii** [comment]
@yannbf  So far, I've fixed some of the same test cases and it worked fine.
I will investigate and deepen my understanding of how the functions are synthesized.
Thank you for your polite answer 🎁

**Comment by yannbf** [comment]
> @yannbf So far, I've fixed some of the same test cases and it worked fine.
> I will investigate and deepen my understanding of how the functions are synthesized.
> Thank you for your polite answer 🎁

Thank you for your interest! I also maintain the msw addon so feel free to share feedback or request features, bug fixes etc! Have a wonderful weekend!

**Comment by takefumi-yoshii** [comment]
> you mentioned that composeStories does not reuse MSW settings. 

@yannbf It's late, but I fixed my [blog](https://zenn.dev/takepepe/articles/reusable-story-playfn#msw-%E3%81%AE%E5%86%8D%E5%88%A9%E7%94%A8). This library is an integral part of my work. thank you for always !

**Comment by yannbf** [comment]
> > you mentioned that composeStories does not reuse MSW settings.
> 
> @yannbf It's late, but I fixed my [blog](https://zenn.dev/takepepe/articles/reusable-story-playfn#msw-%E3%81%AE%E5%86%8D%E5%88%A9%E7%94%A8). This library is an integral part of my work. thank you for always !

You're the best! ♥️

**Pull request merged**
